/* $Id: $ */
package net.sf.gaboto.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from ontologies/FOAF.owl. 
 * 
 * @author Auto-generated by net.sf.gaboto.generation.VocabularyGenerator 
 */
public class FOAFVocab {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    public static OntModel MODEL = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://xmlns.com/foaf/0.1/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = MODEL.createResource( NS );
    
    /** @see net.sf.gaboto.generation.VocabularyGenerator#writeObjectProperties() */
    /** <p>The depiction property is a relationship between a thing and an Image that 
     *  depicts it. As such it is an inverse of the depicts relationship.</p>
     */
    public static final 
    String depiction_URI = "http://xmlns.com/foaf/0.1/depiction";
    public static final 
    ObjectProperty depiction = MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/depiction" );
    
    /** <p>The homepage property relates something to a homepage about it.</p> */
    public static final 
    String homepage_URI = "http://xmlns.com/foaf/0.1/homepage";
    public static final 
    ObjectProperty homepage = MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/homepage" );
    
    
    /** @see net.sf.gaboto.generation.VocabularyGenerator#writeDatatypeProperties() */ 
    
    /** @see net.sf.gaboto.generation.VocabularyGenerator#writeAnnotationProperties() */
    
    /** @see net.sf.gaboto.generation.VocabularyGenerator#writeOntClasses() */
    
    /** @see net.sf.gaboto.generation.VocabularyGenerator#writeOntIndividuals() */
    
}
