/* $Id: $ */
package net.sf.gaboto.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from ontologies/Meter.owl. 
 * 
 * @author Auto-generated by net.sf.gaboto.generation.VocabularyGenerator 
 */
public class MeterVocab {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    public static OntModel MODEL = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/meter/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = MODEL.createResource( NS );
    
    /** @see net.sf.gaboto.generation.VocabularyGenerator#writeObjectProperties() */
    /** <p>Everything that passes through this measure also passed through the upstream 
     *  measure.</p>
     */
    public static final 
    String downstreamOf_URI = "http://purl.org/meter/downstreamOf";
    public static final 
    ObjectProperty downstreamOf = MODEL.createObjectProperty( "http://purl.org/meter/downstreamOf" );
    
    /** <p>A measure provided by this meter.</p> */
    public static final 
    String measure_URI = "http://purl.org/meter/measure";
    public static final 
    ObjectProperty measure = MODEL.createObjectProperty( "http://purl.org/meter/measure" );
    
    /** <p>A resource measured by this measure.</p> */
    public static final 
    String measures_URI = "http://purl.org/meter/measures";
    public static final 
    ObjectProperty measures = MODEL.createObjectProperty( "http://purl.org/meter/measures" );
    
    /** <p>An object supplied by the resource passing through this measure</p> */
    public static final 
    String supplies_URI = "http://purl.org/meter/supplies";
    public static final 
    ObjectProperty supplies = MODEL.createObjectProperty( "http://purl.org/meter/supplies" );
    
    
    /** @see net.sf.gaboto.generation.VocabularyGenerator#writeDatatypeProperties() */ 
    
    /** @see net.sf.gaboto.generation.VocabularyGenerator#writeAnnotationProperties() */
    
    /** @see net.sf.gaboto.generation.VocabularyGenerator#writeOntClasses() */
    /** <p>A conceptual thing relating a meter to something that it measures</p> */
    public static final 
    String Measure_URI = "http://purl.org/meter/Measure";
    public static final 
    OntClass Measure = MODEL.createClass( "http://purl.org/meter/Measure" );
    
    /** <p>A physical entity that provides measures</p> */
    public static final 
    String Meter_URI = "http://purl.org/meter/Meter";
    public static final 
    OntClass Meter = MODEL.createClass( "http://purl.org/meter/Meter" );
    
    
    /** @see net.sf.gaboto.generation.VocabularyGenerator#writeOntIndividuals() */
    
}
