/* $Id: $ */
package net.sf.gaboto.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from ontologies/rdfcon.owl. 
 * 
 * @author Auto-generated by net.sf.gaboto.generation.VacabularyGenerator 
 */
public class RDFCON {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    public static OntModel MODEL = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = MODEL.createResource( NS );
    
    // see VocabularyGenerator#writeObjectProperties()
    public static final 
    String hasContext_URI = "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#hasContext";
    public static final 
    ObjectProperty hasContext = MODEL.createObjectProperty( "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#hasContext" );
    
    public static final 
    String hasDimension_URI = "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#hasDimension";
    public static final 
    ObjectProperty hasDimension = MODEL.createObjectProperty( "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#hasDimension" );
    
    public static final 
    String hasTemporalDimension_URI = "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#hasTemporalDimension";
    public static final 
    ObjectProperty hasTemporalDimension = MODEL.createObjectProperty( "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#hasTemporalDimension" );
    
    
    // see VocabularyGenerator#writeDatatypeProperties()
    
    // see VocabularyGenerator#writeAnnotationProperties()
    
    // see VocabularyGenerator#writeOntClasses()
    public static final 
    String ContextDescriptionGraph_URI = "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#ContextDescriptionGraph";
    public static final 
    OntClass ContextDescriptionGraph = MODEL.createClass( "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#ContextDescriptionGraph" );
    
    public static final 
    String ContextGraph_URI = "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#ContextGraph";
    public static final 
    OntClass ContextGraph = MODEL.createClass( "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#ContextGraph" );
    
    public static final 
    String GlobalKnowledgeGraph_URI = "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#GlobalKnowledgeGraph";
    public static final 
    OntClass GlobalKnowledgeGraph = MODEL.createClass( "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#GlobalKnowledgeGraph" );
    
    public static final 
    String ResourceDescriptionGraph_URI = "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#ResourceDescriptionGraph";
    public static final 
    OntClass ResourceDescriptionGraph = MODEL.createClass( "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#ResourceDescriptionGraph" );
    
    
    // see VocabularyGenerator#writeOntIndividuals()
    
}
