/* $Id: $ */
package net.sf.gaboto.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from ontologies/skos.owl. 
 * 
 * @author Auto-generated by net.sf.gaboto.generation.VocabularyGenerator 
 */
public class SKOSVocab {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    public static OntModel MODEL = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/2004/02/skos/core#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = MODEL.createResource( NS );
    
    /** @see net.sf.gaboto.generation.VocabularyGenerator#writeObjectProperties() */
    public static final 
    String broadMatch_URI = "http://www.w3.org/2004/02/skos/core#broadMatch";
    public static final 
    ObjectProperty broadMatch = MODEL.createObjectProperty( "http://www.w3.org/2004/02/skos/core#broadMatch" );
    
    /** <p>Broader concepts are typically rendered as parents in a concept hierarchy 
     *  (tree).</p>
     */
    public static final 
    String broader_URI = "http://www.w3.org/2004/02/skos/core#broader";
    public static final 
    ObjectProperty broader = MODEL.createObjectProperty( "http://www.w3.org/2004/02/skos/core#broader" );
    
    public static final 
    String broaderTransitive_URI = "http://www.w3.org/2004/02/skos/core#broaderTransitive";
    public static final 
    ObjectProperty broaderTransitive = MODEL.createObjectProperty( "http://www.w3.org/2004/02/skos/core#broaderTransitive" );
    
    public static final 
    String closeMatch_URI = "http://www.w3.org/2004/02/skos/core#closeMatch";
    public static final 
    ObjectProperty closeMatch = MODEL.createObjectProperty( "http://www.w3.org/2004/02/skos/core#closeMatch" );
    
    /** <p>skos:exactMatch is disjoint with each of the properties skos:broadMatch and 
     *  skos:relatedMatch.</p>
     */
    public static final 
    String exactMatch_URI = "http://www.w3.org/2004/02/skos/core#exactMatch";
    public static final 
    ObjectProperty exactMatch = MODEL.createObjectProperty( "http://www.w3.org/2004/02/skos/core#exactMatch" );
    
    public static final 
    String hasTopConcept_URI = "http://www.w3.org/2004/02/skos/core#hasTopConcept";
    public static final 
    ObjectProperty hasTopConcept = MODEL.createObjectProperty( "http://www.w3.org/2004/02/skos/core#hasTopConcept" );
    
    public static final 
    String inScheme_URI = "http://www.w3.org/2004/02/skos/core#inScheme";
    public static final 
    ObjectProperty inScheme = MODEL.createObjectProperty( "http://www.w3.org/2004/02/skos/core#inScheme" );
    
    /** <p>These concept mapping relations mirror semantic relations, and the data model 
     *  defined below is similar (with the exception of skos:exactMatch) to the data 
     *  model defined for semantic relations. A distinct vocabulary is provided for 
     *  concept mapping relations, to provide a convenient way to differentiate links 
     *  within a concept scheme from links between concept schemes. However, this 
     *  pattern of usage is not a formal requirement of the SKOS data model, and relies 
     *  on informal definitions of best practice.</p>
     */
    public static final 
    String mappingRelation_URI = "http://www.w3.org/2004/02/skos/core#mappingRelation";
    public static final 
    ObjectProperty mappingRelation = MODEL.createObjectProperty( "http://www.w3.org/2004/02/skos/core#mappingRelation" );
    
    public static final 
    String member_URI = "http://www.w3.org/2004/02/skos/core#member";
    public static final 
    ObjectProperty member = MODEL.createObjectProperty( "http://www.w3.org/2004/02/skos/core#member" );
    
    /** <p>For any resource, every item in the list given as the value of the skos:memberList 
     *  property is also a value of the skos:member property.</p>
     */
    public static final 
    String memberList_URI = "http://www.w3.org/2004/02/skos/core#memberList";
    public static final 
    ObjectProperty memberList = MODEL.createObjectProperty( "http://www.w3.org/2004/02/skos/core#memberList" );
    
    public static final 
    String narrowMatch_URI = "http://www.w3.org/2004/02/skos/core#narrowMatch";
    public static final 
    ObjectProperty narrowMatch = MODEL.createObjectProperty( "http://www.w3.org/2004/02/skos/core#narrowMatch" );
    
    /** <p>Narrower concepts are typically rendered as children in a concept hierarchy 
     *  (tree).</p>
     */
    public static final 
    String narrower_URI = "http://www.w3.org/2004/02/skos/core#narrower";
    public static final 
    ObjectProperty narrower = MODEL.createObjectProperty( "http://www.w3.org/2004/02/skos/core#narrower" );
    
    public static final 
    String narrowerTransitive_URI = "http://www.w3.org/2004/02/skos/core#narrowerTransitive";
    public static final 
    ObjectProperty narrowerTransitive = MODEL.createObjectProperty( "http://www.w3.org/2004/02/skos/core#narrowerTransitive" );
    
    /** <p>skos:related is disjoint with skos:broaderTransitive</p> */
    public static final 
    String related_URI = "http://www.w3.org/2004/02/skos/core#related";
    public static final 
    ObjectProperty related = MODEL.createObjectProperty( "http://www.w3.org/2004/02/skos/core#related" );
    
    public static final 
    String relatedMatch_URI = "http://www.w3.org/2004/02/skos/core#relatedMatch";
    public static final 
    ObjectProperty relatedMatch = MODEL.createObjectProperty( "http://www.w3.org/2004/02/skos/core#relatedMatch" );
    
    public static final 
    String semanticRelation_URI = "http://www.w3.org/2004/02/skos/core#semanticRelation";
    public static final 
    ObjectProperty semanticRelation = MODEL.createObjectProperty( "http://www.w3.org/2004/02/skos/core#semanticRelation" );
    
    public static final 
    String topConceptOf_URI = "http://www.w3.org/2004/02/skos/core#topConceptOf";
    public static final 
    ObjectProperty topConceptOf = MODEL.createObjectProperty( "http://www.w3.org/2004/02/skos/core#topConceptOf" );
    
    
    /** @see net.sf.gaboto.generation.VocabularyGenerator#writeDatatypeProperties() */ 
    public static final 
    String notation_URI = "http://www.w3.org/2004/02/skos/core#notation";
    public static final 
    DatatypeProperty notation = MODEL.createDatatypeProperty( "http://www.w3.org/2004/02/skos/core#notation" );
    
    
    /** @see net.sf.gaboto.generation.VocabularyGenerator#writeAnnotationProperties() */
    /** <p>The range of skos:altLabel is the class of RDF plain literals.skos:prefLabel, 
     *  skos:altLabel and skos:hiddenLabel are pairwise disjoint properties.</p>
     */
    public static final 
    String altLabel_URI = "http://www.w3.org/2004/02/skos/core#altLabel";
    public static final 
    AnnotationProperty altLabel = MODEL.createAnnotationProperty( "http://www.w3.org/2004/02/skos/core#altLabel" );
    
    public static final 
    String changeNote_URI = "http://www.w3.org/2004/02/skos/core#changeNote";
    public static final 
    AnnotationProperty changeNote = MODEL.createAnnotationProperty( "http://www.w3.org/2004/02/skos/core#changeNote" );
    
    public static final 
    String definition_URI = "http://www.w3.org/2004/02/skos/core#definition";
    public static final 
    AnnotationProperty definition = MODEL.createAnnotationProperty( "http://www.w3.org/2004/02/skos/core#definition" );
    
    public static final 
    String editorialNote_URI = "http://www.w3.org/2004/02/skos/core#editorialNote";
    public static final 
    AnnotationProperty editorialNote = MODEL.createAnnotationProperty( "http://www.w3.org/2004/02/skos/core#editorialNote" );
    
    public static final 
    String example_URI = "http://www.w3.org/2004/02/skos/core#example";
    public static final 
    AnnotationProperty example = MODEL.createAnnotationProperty( "http://www.w3.org/2004/02/skos/core#example" );
    
    /** <p>The range of skos:hiddenLabel is the class of RDF plain literals.skos:prefLabel, 
     *  skos:altLabel and skos:hiddenLabel are pairwise disjoint properties.</p>
     */
    public static final 
    String hiddenLabel_URI = "http://www.w3.org/2004/02/skos/core#hiddenLabel";
    public static final 
    AnnotationProperty hiddenLabel = MODEL.createAnnotationProperty( "http://www.w3.org/2004/02/skos/core#hiddenLabel" );
    
    public static final 
    String historyNote_URI = "http://www.w3.org/2004/02/skos/core#historyNote";
    public static final 
    AnnotationProperty historyNote = MODEL.createAnnotationProperty( "http://www.w3.org/2004/02/skos/core#historyNote" );
    
    public static final 
    String note_URI = "http://www.w3.org/2004/02/skos/core#note";
    public static final 
    AnnotationProperty note = MODEL.createAnnotationProperty( "http://www.w3.org/2004/02/skos/core#note" );
    
    /** <p>skos:prefLabel, skos:altLabel and skos:hiddenLabel are pairwise disjoint properties.A 
     *  resource has no more than one value of skos:prefLabel per language tag, and 
     *  no more than one value of skos:prefLabel without language tag.The range of 
     *  skos:prefLabel is the class of RDF plain literals.</p>
     */
    public static final 
    String prefLabel_URI = "http://www.w3.org/2004/02/skos/core#prefLabel";
    public static final 
    AnnotationProperty prefLabel = MODEL.createAnnotationProperty( "http://www.w3.org/2004/02/skos/core#prefLabel" );
    
    public static final 
    String scopeNote_URI = "http://www.w3.org/2004/02/skos/core#scopeNote";
    public static final 
    AnnotationProperty scopeNote = MODEL.createAnnotationProperty( "http://www.w3.org/2004/02/skos/core#scopeNote" );
    
    
    /** @see net.sf.gaboto.generation.VocabularyGenerator#writeOntClasses() */
    public static final 
    String Collection_URI = "http://www.w3.org/2004/02/skos/core#Collection";
    public static final 
    OntClass Collection = MODEL.createClass( "http://www.w3.org/2004/02/skos/core#Collection" );
    
    public static final 
    String Concept_URI = "http://www.w3.org/2004/02/skos/core#Concept";
    public static final 
    OntClass Concept = MODEL.createClass( "http://www.w3.org/2004/02/skos/core#Concept" );
    
    public static final 
    String ConceptScheme_URI = "http://www.w3.org/2004/02/skos/core#ConceptScheme";
    public static final 
    OntClass ConceptScheme = MODEL.createClass( "http://www.w3.org/2004/02/skos/core#ConceptScheme" );
    
    public static final 
    String OrderedCollection_URI = "http://www.w3.org/2004/02/skos/core#OrderedCollection";
    public static final 
    OntClass OrderedCollection = MODEL.createClass( "http://www.w3.org/2004/02/skos/core#OrderedCollection" );
    
    
    /** @see net.sf.gaboto.generation.VocabularyGenerator#writeOntIndividuals() */
    
}
