/* $Id: $ */
package net.sf.gaboto.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from ontologies/Time.owl. 
 * 
 * @author Auto-generated by net.sf.gaboto.generation.VocabularyGenerator 
 */
public class TimeVocab {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    public static OntModel MODEL = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/2006/time#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = MODEL.createResource( NS );
    
    /** @see net.sf.gaboto.generation.VocabularyGenerator#writeObjectProperties() */
    public static final 
    String after_URI = "http://www.w3.org/2006/time#after";
    public static final 
    ObjectProperty after = MODEL.createObjectProperty( "http://www.w3.org/2006/time#after" );
    
    public static final 
    String before_URI = "http://www.w3.org/2006/time#before";
    public static final 
    ObjectProperty before = MODEL.createObjectProperty( "http://www.w3.org/2006/time#before" );
    
    public static final 
    String dayOfWeek_URI = "http://www.w3.org/2006/time#dayOfWeek";
    public static final 
    ObjectProperty dayOfWeek = MODEL.createObjectProperty( "http://www.w3.org/2006/time#dayOfWeek" );
    
    public static final 
    String hasBeginning_URI = "http://www.w3.org/2006/time#hasBeginning";
    public static final 
    ObjectProperty hasBeginning = MODEL.createObjectProperty( "http://www.w3.org/2006/time#hasBeginning" );
    
    public static final 
    String hasDateTimeDescription_URI = "http://www.w3.org/2006/time#hasDateTimeDescription";
    public static final 
    ObjectProperty hasDateTimeDescription = MODEL.createObjectProperty( "http://www.w3.org/2006/time#hasDateTimeDescription" );
    
    public static final 
    String hasDurationDescription_URI = "http://www.w3.org/2006/time#hasDurationDescription";
    public static final 
    ObjectProperty hasDurationDescription = MODEL.createObjectProperty( "http://www.w3.org/2006/time#hasDurationDescription" );
    
    public static final 
    String hasEnd_URI = "http://www.w3.org/2006/time#hasEnd";
    public static final 
    ObjectProperty hasEnd = MODEL.createObjectProperty( "http://www.w3.org/2006/time#hasEnd" );
    
    public static final 
    String inDateTime_URI = "http://www.w3.org/2006/time#inDateTime";
    public static final 
    ObjectProperty inDateTime = MODEL.createObjectProperty( "http://www.w3.org/2006/time#inDateTime" );
    
    public static final 
    String inside_URI = "http://www.w3.org/2006/time#inside";
    public static final 
    ObjectProperty inside = MODEL.createObjectProperty( "http://www.w3.org/2006/time#inside" );
    
    public static final 
    String intervalAfter_URI = "http://www.w3.org/2006/time#intervalAfter";
    public static final 
    ObjectProperty intervalAfter = MODEL.createObjectProperty( "http://www.w3.org/2006/time#intervalAfter" );
    
    public static final 
    String intervalBefore_URI = "http://www.w3.org/2006/time#intervalBefore";
    public static final 
    ObjectProperty intervalBefore = MODEL.createObjectProperty( "http://www.w3.org/2006/time#intervalBefore" );
    
    public static final 
    String intervalContains_URI = "http://www.w3.org/2006/time#intervalContains";
    public static final 
    ObjectProperty intervalContains = MODEL.createObjectProperty( "http://www.w3.org/2006/time#intervalContains" );
    
    public static final 
    String intervalDuring_URI = "http://www.w3.org/2006/time#intervalDuring";
    public static final 
    ObjectProperty intervalDuring = MODEL.createObjectProperty( "http://www.w3.org/2006/time#intervalDuring" );
    
    public static final 
    String intervalEquals_URI = "http://www.w3.org/2006/time#intervalEquals";
    public static final 
    ObjectProperty intervalEquals = MODEL.createObjectProperty( "http://www.w3.org/2006/time#intervalEquals" );
    
    public static final 
    String intervalFinishedBy_URI = "http://www.w3.org/2006/time#intervalFinishedBy";
    public static final 
    ObjectProperty intervalFinishedBy = MODEL.createObjectProperty( "http://www.w3.org/2006/time#intervalFinishedBy" );
    
    public static final 
    String intervalFinishes_URI = "http://www.w3.org/2006/time#intervalFinishes";
    public static final 
    ObjectProperty intervalFinishes = MODEL.createObjectProperty( "http://www.w3.org/2006/time#intervalFinishes" );
    
    public static final 
    String intervalMeets_URI = "http://www.w3.org/2006/time#intervalMeets";
    public static final 
    ObjectProperty intervalMeets = MODEL.createObjectProperty( "http://www.w3.org/2006/time#intervalMeets" );
    
    public static final 
    String intervalMetBy_URI = "http://www.w3.org/2006/time#intervalMetBy";
    public static final 
    ObjectProperty intervalMetBy = MODEL.createObjectProperty( "http://www.w3.org/2006/time#intervalMetBy" );
    
    public static final 
    String intervalOverlappedBy_URI = "http://www.w3.org/2006/time#intervalOverlappedBy";
    public static final 
    ObjectProperty intervalOverlappedBy = MODEL.createObjectProperty( "http://www.w3.org/2006/time#intervalOverlappedBy" );
    
    public static final 
    String intervalOverlaps_URI = "http://www.w3.org/2006/time#intervalOverlaps";
    public static final 
    ObjectProperty intervalOverlaps = MODEL.createObjectProperty( "http://www.w3.org/2006/time#intervalOverlaps" );
    
    public static final 
    String intervalStartedBy_URI = "http://www.w3.org/2006/time#intervalStartedBy";
    public static final 
    ObjectProperty intervalStartedBy = MODEL.createObjectProperty( "http://www.w3.org/2006/time#intervalStartedBy" );
    
    public static final 
    String intervalStarts_URI = "http://www.w3.org/2006/time#intervalStarts";
    public static final 
    ObjectProperty intervalStarts = MODEL.createObjectProperty( "http://www.w3.org/2006/time#intervalStarts" );
    
    public static final 
    String timeZone_URI = "http://www.w3.org/2006/time#timeZone";
    public static final 
    ObjectProperty timeZone = MODEL.createObjectProperty( "http://www.w3.org/2006/time#timeZone" );
    
    public static final 
    String unitType_URI = "http://www.w3.org/2006/time#unitType";
    public static final 
    ObjectProperty unitType = MODEL.createObjectProperty( "http://www.w3.org/2006/time#unitType" );
    
    
    /** @see net.sf.gaboto.generation.VocabularyGenerator#writeDatatypeProperties() */ 
    public static final 
    String day_URI = "http://www.w3.org/2006/time#day";
    public static final 
    DatatypeProperty day = MODEL.createDatatypeProperty( "http://www.w3.org/2006/time#day" );
    
    public static final 
    String dayOfYear_URI = "http://www.w3.org/2006/time#dayOfYear";
    public static final 
    DatatypeProperty dayOfYear = MODEL.createDatatypeProperty( "http://www.w3.org/2006/time#dayOfYear" );
    
    public static final 
    String days_URI = "http://www.w3.org/2006/time#days";
    public static final 
    DatatypeProperty days = MODEL.createDatatypeProperty( "http://www.w3.org/2006/time#days" );
    
    public static final 
    String hour_URI = "http://www.w3.org/2006/time#hour";
    public static final 
    DatatypeProperty hour = MODEL.createDatatypeProperty( "http://www.w3.org/2006/time#hour" );
    
    public static final 
    String hours_URI = "http://www.w3.org/2006/time#hours";
    public static final 
    DatatypeProperty hours = MODEL.createDatatypeProperty( "http://www.w3.org/2006/time#hours" );
    
    public static final 
    String inXSDDateTime_URI = "http://www.w3.org/2006/time#inXSDDateTime";
    public static final 
    DatatypeProperty inXSDDateTime = MODEL.createDatatypeProperty( "http://www.w3.org/2006/time#inXSDDateTime" );
    
    public static final 
    String minute_URI = "http://www.w3.org/2006/time#minute";
    public static final 
    DatatypeProperty minute = MODEL.createDatatypeProperty( "http://www.w3.org/2006/time#minute" );
    
    public static final 
    String minutes_URI = "http://www.w3.org/2006/time#minutes";
    public static final 
    DatatypeProperty minutes = MODEL.createDatatypeProperty( "http://www.w3.org/2006/time#minutes" );
    
    public static final 
    String month_URI = "http://www.w3.org/2006/time#month";
    public static final 
    DatatypeProperty month = MODEL.createDatatypeProperty( "http://www.w3.org/2006/time#month" );
    
    public static final 
    String months_URI = "http://www.w3.org/2006/time#months";
    public static final 
    DatatypeProperty months = MODEL.createDatatypeProperty( "http://www.w3.org/2006/time#months" );
    
    public static final 
    String second_URI = "http://www.w3.org/2006/time#second";
    public static final 
    DatatypeProperty second = MODEL.createDatatypeProperty( "http://www.w3.org/2006/time#second" );
    
    public static final 
    String seconds_URI = "http://www.w3.org/2006/time#seconds";
    public static final 
    DatatypeProperty seconds = MODEL.createDatatypeProperty( "http://www.w3.org/2006/time#seconds" );
    
    public static final 
    String week_URI = "http://www.w3.org/2006/time#week";
    public static final 
    DatatypeProperty week = MODEL.createDatatypeProperty( "http://www.w3.org/2006/time#week" );
    
    public static final 
    String weeks_URI = "http://www.w3.org/2006/time#weeks";
    public static final 
    DatatypeProperty weeks = MODEL.createDatatypeProperty( "http://www.w3.org/2006/time#weeks" );
    
    public static final 
    String xsdDateTime_URI = "http://www.w3.org/2006/time#xsdDateTime";
    public static final 
    DatatypeProperty xsdDateTime = MODEL.createDatatypeProperty( "http://www.w3.org/2006/time#xsdDateTime" );
    
    public static final 
    String year_URI = "http://www.w3.org/2006/time#year";
    public static final 
    DatatypeProperty year = MODEL.createDatatypeProperty( "http://www.w3.org/2006/time#year" );
    
    public static final 
    String years_URI = "http://www.w3.org/2006/time#years";
    public static final 
    DatatypeProperty years = MODEL.createDatatypeProperty( "http://www.w3.org/2006/time#years" );
    
    
    /** @see net.sf.gaboto.generation.VocabularyGenerator#writeAnnotationProperties() */
    
    /** @see net.sf.gaboto.generation.VocabularyGenerator#writeOntClasses() */
    public static final 
    String DateTimeDescription_URI = "http://www.w3.org/2006/time#DateTimeDescription";
    public static final 
    OntClass DateTimeDescription = MODEL.createClass( "http://www.w3.org/2006/time#DateTimeDescription" );
    
    public static final 
    String DateTimeInterval_URI = "http://www.w3.org/2006/time#DateTimeInterval";
    public static final 
    OntClass DateTimeInterval = MODEL.createClass( "http://www.w3.org/2006/time#DateTimeInterval" );
    
    public static final 
    String DayOfWeek_URI = "http://www.w3.org/2006/time#DayOfWeek";
    public static final 
    OntClass DayOfWeek = MODEL.createClass( "http://www.w3.org/2006/time#DayOfWeek" );
    
    public static final 
    String DurationDescription_URI = "http://www.w3.org/2006/time#DurationDescription";
    public static final 
    OntClass DurationDescription = MODEL.createClass( "http://www.w3.org/2006/time#DurationDescription" );
    
    public static final 
    String Instant_URI = "http://www.w3.org/2006/time#Instant";
    public static final 
    OntClass Instant = MODEL.createClass( "http://www.w3.org/2006/time#Instant" );
    
    public static final 
    String Interval_URI = "http://www.w3.org/2006/time#Interval";
    public static final 
    OntClass Interval = MODEL.createClass( "http://www.w3.org/2006/time#Interval" );
    
    public static final 
    String January_URI = "http://www.w3.org/2006/time#January";
    public static final 
    OntClass January = MODEL.createClass( "http://www.w3.org/2006/time#January" );
    
    public static final 
    String ProperInterval_URI = "http://www.w3.org/2006/time#ProperInterval";
    public static final 
    OntClass ProperInterval = MODEL.createClass( "http://www.w3.org/2006/time#ProperInterval" );
    
    public static final 
    String TemporalEntity_URI = "http://www.w3.org/2006/time#TemporalEntity";
    public static final 
    OntClass TemporalEntity = MODEL.createClass( "http://www.w3.org/2006/time#TemporalEntity" );
    
    public static final 
    String TemporalUnit_URI = "http://www.w3.org/2006/time#TemporalUnit";
    public static final 
    OntClass TemporalUnit = MODEL.createClass( "http://www.w3.org/2006/time#TemporalUnit" );
    
    public static final 
    String Year_URI = "http://www.w3.org/2006/time#Year";
    public static final 
    OntClass Year = MODEL.createClass( "http://www.w3.org/2006/time#Year" );
    
    
    /** @see net.sf.gaboto.generation.VocabularyGenerator#writeOntIndividuals() */
    public static final Individual Friday = MODEL.createIndividual( "http://www.w3.org/2006/time#Friday", DayOfWeek );
    
    public static final Individual Monday = MODEL.createIndividual( "http://www.w3.org/2006/time#Monday", DayOfWeek );
    
    public static final Individual Saturday = MODEL.createIndividual( "http://www.w3.org/2006/time#Saturday", DayOfWeek );
    
    public static final Individual Sunday = MODEL.createIndividual( "http://www.w3.org/2006/time#Sunday", DayOfWeek );
    
    public static final Individual Thursday = MODEL.createIndividual( "http://www.w3.org/2006/time#Thursday", DayOfWeek );
    
    public static final Individual Tuesday = MODEL.createIndividual( "http://www.w3.org/2006/time#Tuesday", DayOfWeek );
    
    public static final Individual Wednesday = MODEL.createIndividual( "http://www.w3.org/2006/time#Wednesday", DayOfWeek );
    
    public static final Individual unitDay = MODEL.createIndividual( "http://www.w3.org/2006/time#unitDay", TemporalUnit );
    
    public static final Individual unitHour = MODEL.createIndividual( "http://www.w3.org/2006/time#unitHour", TemporalUnit );
    
    public static final Individual unitMinute = MODEL.createIndividual( "http://www.w3.org/2006/time#unitMinute", TemporalUnit );
    
    public static final Individual unitMonth = MODEL.createIndividual( "http://www.w3.org/2006/time#unitMonth", TemporalUnit );
    
    public static final Individual unitSecond = MODEL.createIndividual( "http://www.w3.org/2006/time#unitSecond", TemporalUnit );
    
    public static final Individual unitWeek = MODEL.createIndividual( "http://www.w3.org/2006/time#unitWeek", TemporalUnit );
    
    public static final Individual unitYear = MODEL.createIndividual( "http://www.w3.org/2006/time#unitYear", TemporalUnit );
    
    
}
