package org.oucs.gaboto.entities;

import java.util.HashMap;
import java.util.Map;
import java.util.Collection;
import java.util.HashSet;
import java.util.Set;
import java.util.List;
import java.util.ArrayList;
import java.lang.reflect.Method;
import org.oucs.gaboto.entities.utils.SimpleLiteralProperty;
import org.oucs.gaboto.entities.utils.SimpleURIProperty;
import org.oucs.gaboto.entities.utils.ComplexProperty;
import org.oucs.gaboto.entities.utils.BagURIProperty;
import org.oucs.gaboto.entities.utils.BagLiteralProperty;
import org.oucs.gaboto.entities.utils.BagComplexProperty;
import org.oucs.gaboto.entities.utils.IndirectProperty;
import org.oucs.gaboto.entities.utils.UnstoredProperty;
import org.oucs.gaboto.entities.utils.PassiveProperty;
import org.oucs.gaboto.entities.utils.StaticProperty;
import org.oucs.gaboto.vocabulary.*;
import org.oucs.gaboto.entities.GabotoEntity;
import org.oucs.gaboto.entities.pool.GabotoEntityPool;
import org.oucs.gaboto.entities.pool.EntityExistsCallback;
import org.oucs.gaboto.entities.pool.PassiveEntitiesRequest;
import org.oucs.gaboto.model.GabotoSnapshot;
import com.hp.hpl.jena.rdf.model.Resource;
import com.hp.hpl.jena.rdf.model.Statement;
import com.hp.hpl.jena.rdf.model.StmtIterator;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.Literal;
import com.hp.hpl.jena.rdf.model.Bag;
import com.hp.hpl.jena.rdf.model.NodeIterator;
import com.hp.hpl.jena.rdf.model.RDFNode;
import com.hp.hpl.jena.ontology.OntClass;
import org.oucs.gaboto.entities.OxpEntity;


/**
 *<p>This class was automatically generated by Gaboto<p>
 */
public class Website extends OxpEntity {
	private Collection<OxpEntity> isWeblearnIn;
	private Collection<OxpEntity> isITHomepageIn;
	private Collection<OxpEntity> isHomepageIn;
	private Collection<OxpEntity> isLibraryHomepageIn;


	private static Map<String, List<Method>> indirectPropertyLookupTable;
	static{
		indirectPropertyLookupTable = new HashMap<String, List<Method>>();
		List<Method> list;

		try{
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	@Override
	public String getType(){
		return "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Website";
	}

	@PassiveProperty(
		uri = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasWeblearn",
		entity = "OxpEntity"
	)
	public Collection<OxpEntity> getIsWeblearnIn(){
		if(! isPassiveEntitiesLoaded() )
			loadPassiveEntities();
		return this.isWeblearnIn;
	}

	@PassiveProperty(
		uri = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasWeblearn",
		entity = "OxpEntity"
	)
	private void setIsWeblearnIn(Collection<OxpEntity> isWeblearnIn){
		this.isWeblearnIn = isWeblearnIn;
	}

	private void addIsWeblearnIn(OxpEntity isWeblearnIn){
		if(null == this.isWeblearnIn)
			this.isWeblearnIn = new HashSet<OxpEntity>();
		this.isWeblearnIn.add(isWeblearnIn);
	}

	@PassiveProperty(
		uri = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasITHomepage",
		entity = "OxpEntity"
	)
	public Collection<OxpEntity> getIsITHomepageIn(){
		if(! isPassiveEntitiesLoaded() )
			loadPassiveEntities();
		return this.isITHomepageIn;
	}

	@PassiveProperty(
		uri = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasITHomepage",
		entity = "OxpEntity"
	)
	private void setIsITHomepageIn(Collection<OxpEntity> isITHomepageIn){
		this.isITHomepageIn = isITHomepageIn;
	}

	private void addIsITHomepageIn(OxpEntity isITHomepageIn){
		if(null == this.isITHomepageIn)
			this.isITHomepageIn = new HashSet<OxpEntity>();
		this.isITHomepageIn.add(isITHomepageIn);
	}

	@PassiveProperty(
		uri = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasHomepage",
		entity = "OxpEntity"
	)
	public Collection<OxpEntity> getIsHomepageIn(){
		if(! isPassiveEntitiesLoaded() )
			loadPassiveEntities();
		return this.isHomepageIn;
	}

	@PassiveProperty(
		uri = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasHomepage",
		entity = "OxpEntity"
	)
	private void setIsHomepageIn(Collection<OxpEntity> isHomepageIn){
		this.isHomepageIn = isHomepageIn;
	}

	private void addIsHomepageIn(OxpEntity isHomepageIn){
		if(null == this.isHomepageIn)
			this.isHomepageIn = new HashSet<OxpEntity>();
		this.isHomepageIn.add(isHomepageIn);
	}

	@PassiveProperty(
		uri = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasLibraryHomepage",
		entity = "OxpEntity"
	)
	public Collection<OxpEntity> getIsLibraryHomepageIn(){
		if(! isPassiveEntitiesLoaded() )
			loadPassiveEntities();
		return this.isLibraryHomepageIn;
	}

	@PassiveProperty(
		uri = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasLibraryHomepage",
		entity = "OxpEntity"
	)
	private void setIsLibraryHomepageIn(Collection<OxpEntity> isLibraryHomepageIn){
		this.isLibraryHomepageIn = isLibraryHomepageIn;
	}

	private void addIsLibraryHomepageIn(OxpEntity isLibraryHomepageIn){
		if(null == this.isLibraryHomepageIn)
			this.isLibraryHomepageIn = new HashSet<OxpEntity>();
		this.isLibraryHomepageIn.add(isLibraryHomepageIn);
	}







	public Collection<PassiveEntitiesRequest> getPassiveEntitiesRequest(){
		Collection<PassiveEntitiesRequest> requests = super.getPassiveEntitiesRequest();
		if(null == requests)
			requests = new HashSet<PassiveEntitiesRequest>();
		requests.add(new PassiveEntitiesRequest(){
			public String getType() {
				return "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#OxpEntity";
			}

			public String getUri() {
				return "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasWeblearn";
			}

			public int getCollectionType() {
				return GabotoEntityPool.PASSIVE_PROPERTY_COLLECTION_TYPE_NONE;
			}

			public void passiveEntityLoaded(GabotoEntity entity) {
				addIsWeblearnIn((OxpEntity)entity);
			}
		});
		requests.add(new PassiveEntitiesRequest(){
			public String getType() {
				return "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#OxpEntity";
			}

			public String getUri() {
				return "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasITHomepage";
			}

			public int getCollectionType() {
				return GabotoEntityPool.PASSIVE_PROPERTY_COLLECTION_TYPE_NONE;
			}

			public void passiveEntityLoaded(GabotoEntity entity) {
				addIsITHomepageIn((OxpEntity)entity);
			}
		});
		requests.add(new PassiveEntitiesRequest(){
			public String getType() {
				return "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#OxpEntity";
			}

			public String getUri() {
				return "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasHomepage";
			}

			public int getCollectionType() {
				return GabotoEntityPool.PASSIVE_PROPERTY_COLLECTION_TYPE_NONE;
			}

			public void passiveEntityLoaded(GabotoEntity entity) {
				addIsHomepageIn((OxpEntity)entity);
			}
		});
		requests.add(new PassiveEntitiesRequest(){
			public String getType() {
				return "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#OxpEntity";
			}

			public String getUri() {
				return "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasLibraryHomepage";
			}

			public int getCollectionType() {
				return GabotoEntityPool.PASSIVE_PROPERTY_COLLECTION_TYPE_NONE;
			}

			public void passiveEntityLoaded(GabotoEntity entity) {
				addIsLibraryHomepageIn((OxpEntity)entity);
			}
		});
		return requests;
	}


	protected List<Method> getIndirectMethodsForProperty(String propertyURI){
		List<Method> list = super.getIndirectMethodsForProperty(propertyURI);
		if(null == list)
			return indirectPropertyLookupTable.get(propertyURI);
		
		else{
			List<Method> tmp = indirectPropertyLookupTable.get(propertyURI);
			if(null != tmp)
				list.addAll(tmp);
		}
		return list;
	}

}