/* $Id: $ */
package org.oucs.gaboto.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from ontologies/gaboto.owl. 
 * 
 * @author Auto-generated by net.sf.gaboto.generation.VacabularyGenerator 
 */
public class GabotoVocab {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    public static OntModel MODEL = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://ns.ox.ac.uk/namespace/gaboto/2009/03/owl#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = MODEL.createResource( NS );
    
    // see VocabularyGenerator#writeObjectProperties()
    
    // see VocabularyGenerator#writeDatatypeProperties()
    
    // see VocabularyGenerator#writeAnnotationProperties()
    
    // see VocabularyGenerator#writeOntClasses()
    
    // see VocabularyGenerator#writeOntIndividuals()
    
}
