/* CVS $Id: $ */
package org.oucs.gaboto.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from ontologies/oxpoints.owl 
 * @author Auto-generated by schemagen on 11 Mar 2009 08:56 
 */
public class OxPointsVocab {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>Defines that two entities are associated with one another (N:M)</p> */
    
    public static final String associatedWith_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#associatedWith";
    public static final ObjectProperty associatedWith = m_model.createObjectProperty( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#associatedWith" );
        
    
    /** <p>Can for example be used to describe the capacity of carparks</p> */
    
    public static final String capacity_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#capacity";
    public static final ObjectProperty capacity = m_model.createObjectProperty( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#capacity" );
        
    
    /** <p>describe the width of an entity</p> */
    
    public static final String hasHeight_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasHeight";
    public static final ObjectProperty hasHeight = m_model.createObjectProperty( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasHeight" );
        
    
    /** <p>Describes that an entity has a homepage</p> */
    
    public static final String hasHomepage_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasHomepage";
    public static final ObjectProperty hasHomepage = m_model.createObjectProperty( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasHomepage" );
        
    
    /** <p>Describes that an entity has a homepage for its it people</p> */
    
    public static final String hasITHomepage_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasITHomepage";
    public static final ObjectProperty hasITHomepage = m_model.createObjectProperty( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasITHomepage" );
        
    
    /** <p>Library Homepage</p> */
    
    public static final String hasLibraryHomepage_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasLibraryHomepage";
    public static final ObjectProperty hasLibraryHomepage = m_model.createObjectProperty( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasLibraryHomepage" );
        
    
    /** <p>Describes that an entity has a specific location</p> */
    
    public static final String hasLocation_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasLocation";
    public static final ObjectProperty hasLocation = m_model.createObjectProperty( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasLocation" );
        
    
    /** <p>The naming scheme of entities introduced by OLIS</p> */
    
    public static final String hasOLISCode_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasOLISCode";
    public static final ObjectProperty hasOLISCode = m_model.createObjectProperty( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasOLISCode" );
        
    
    /** <p>The naming scheme of entities introduced by OUCS</p> */
    
    public static final String hasOUCSCode_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasOUCSCode";
    public static final ObjectProperty hasOUCSCode = m_model.createObjectProperty( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasOUCSCode" );
        
    
    /** <p>Defines the primary place for an entity</p> */
    
    public static final String hasPrimaryPlace_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasPrimaryPlace";
    public static final ObjectProperty hasPrimaryPlace = m_model.createObjectProperty( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasPrimaryPlace" );
        
    
    /** <p>Describes that an entity has a weblearn</p> */
    
    public static final String hasWeblearn_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasWeblearn";
    public static final ObjectProperty hasWeblearn = m_model.createObjectProperty( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasWeblearn" );
        
    
    /** <p>describe the width of an entity</p> */
    
    public static final String hasWidth_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasWidth";
    public static final ObjectProperty hasWidth = m_model.createObjectProperty( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#hasWidth" );
        
    
    /** <p></p> */
    
    public static final String inImage_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#inImage";
    public static final ObjectProperty inImage = m_model.createObjectProperty( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#inImage" );
        
    
    /** <p>Describes that a unit occupies a place</p> */
    
    public static final String occupies_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#occupies";
    public static final ObjectProperty occupies = m_model.createObjectProperty( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#occupies" );
        
    
    /** <p>Describes that a place is physically located within another place</p> */
    
    public static final String physicallyContainedWithin_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#physicallyContainedWithin";
    public static final ObjectProperty physicallyContainedWithin = m_model.createObjectProperty( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#physicallyContainedWithin" );
        
    
    /** <p>Defines that an entity is a subset of another entity (1:N)</p> */
    
    public static final String subsetOf_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#subsetOf";
    public static final ObjectProperty subsetOf = m_model.createObjectProperty( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#subsetOf" );
        
    
    
    public static final String uses_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#uses";
    public static final ObjectProperty uses = m_model.createObjectProperty( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#uses" );
        
    
    
    public static final String Building_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Building";
    public static final OntClass Building = m_model.createClass( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Building" );
        
    
    
    public static final String Carpark_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Carpark";
    public static final OntClass Carpark = m_model.createClass( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Carpark" );
        
    
    
    public static final String College_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#College";
    public static final OntClass College = m_model.createClass( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#College" );
        
    
    
    public static final String Department_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Department";
    public static final OntClass Department = m_model.createClass( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Department" );
        
    
    
    public static final String Division_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Division";
    public static final OntClass Division = m_model.createClass( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Division" );
        
    
    
    public static final String DrainCover_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#DrainCover";
    public static final OntClass DrainCover = m_model.createClass( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#DrainCover" );
        
    
    
    public static final String Entrance_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Entrance";
    public static final OntClass Entrance = m_model.createClass( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Entrance" );
        
    
    
    public static final String Faculty_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Faculty";
    public static final OntClass Faculty = m_model.createClass( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Faculty" );
        
    
    
    public static final String Group_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Group";
    public static final OntClass Group = m_model.createClass( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Group" );
        
    
    
    public static final String Image_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Image";
    public static final OntClass Image = m_model.createClass( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Image" );
        
    
    /** <p>Describes any kind of library.</p> */
    
    public static final String Library_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Library";
    public static final OntClass Library = m_model.createClass( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Library" );
        
    
    /** <p>Describes any kind of museum.</p> */
    
    public static final String Museum_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Museum";
    public static final OntClass Museum = m_model.createClass( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Museum" );
        
    
    
    public static final String OxpEntity_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#OxpEntity";
    public static final OntClass OxpEntity = m_model.createClass( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#OxpEntity" );
        
    
    
    public static final String Place_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Place";
    public static final OntClass Place = m_model.createClass( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Place" );
        
    
    
    public static final String Room_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Room";
    public static final OntClass Room = m_model.createClass( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Room" );
        
    
    
    public static final String ServiceDepartment_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#ServiceDepartment";
    public static final OntClass ServiceDepartment = m_model.createClass( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#ServiceDepartment" );
        
    
    
    public static final String Site_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Site";
    public static final OntClass Site = m_model.createClass( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Site" );
        
    
    
    public static final String Unit_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Unit";
    public static final OntClass Unit = m_model.createClass( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Unit" );
        
    
    
    public static final String WAP_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#WAP";
    public static final OntClass WAP = m_model.createClass( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#WAP" );
        
    
    
    public static final String Website_URI = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Website";
    public static final OntClass Website = m_model.createClass( "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Website" );
        
    
}
