/* $Id: $ */
package org.oucs.gaboto.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from ontologies/vCard.owl. 
 * 
 * @author Auto-generated by net.sf.gaboto.generation.VacabularyGenerator 
 */
public class VCard {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    public static OntModel MODEL = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://nwalsh.com/rdf/vCard#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = MODEL.createResource( NS );
    
    // see VocabularyGenerator#writeObjectProperties()
    /** <p>A postal or street address of a person.</p> */
    public static final 
    String adr_URI = "http://nwalsh.com/rdf/vCard#adr";
    public static final 
    ObjectProperty adr = MODEL.createObjectProperty( "http://nwalsh.com/rdf/vCard#adr" );
    
    /** <p>A person that acts as one's agent.</p> */
    public static final 
    String agent_URI = "http://nwalsh.com/rdf/vCard#agent";
    public static final 
    ObjectProperty agent = MODEL.createObjectProperty( "http://nwalsh.com/rdf/vCard#agent" );
    
    /** <p>An email address.</p> */
    public static final 
    String email_URI = "http://nwalsh.com/rdf/vCard#email";
    public static final 
    ObjectProperty email = MODEL.createObjectProperty( "http://nwalsh.com/rdf/vCard#email" );
    
    /** <p>A fax number of a person.</p> */
    public static final 
    String fax_URI = "http://nwalsh.com/rdf/vCard#fax";
    public static final 
    ObjectProperty fax = MODEL.createObjectProperty( "http://nwalsh.com/rdf/vCard#fax" );
    
    /** <p>A geographic location associated with a person.</p> */
    public static final 
    String geo_URI = "http://nwalsh.com/rdf/vCard#geo";
    public static final 
    ObjectProperty geo = MODEL.createObjectProperty( "http://nwalsh.com/rdf/vCard#geo" );
    
    /** <p>A home address of a person.</p> */
    public static final 
    String homeAdr_URI = "http://nwalsh.com/rdf/vCard#homeAdr";
    public static final 
    ObjectProperty homeAdr = MODEL.createObjectProperty( "http://nwalsh.com/rdf/vCard#homeAdr" );
    
    /** <p>A home phone number of a person.</p> */
    public static final 
    String homeTel_URI = "http://nwalsh.com/rdf/vCard#homeTel";
    public static final 
    ObjectProperty homeTel = MODEL.createObjectProperty( "http://nwalsh.com/rdf/vCard#homeTel" );
    
    /** <p>A key (e.g, PKI key) of a person.</p> */
    public static final 
    String key_URI = "http://nwalsh.com/rdf/vCard#key";
    public static final 
    ObjectProperty key = MODEL.createObjectProperty( "http://nwalsh.com/rdf/vCard#key" );
    
    /** <p>A logo associated with a person or their organization.</p> */
    public static final 
    String logo_URI = "http://nwalsh.com/rdf/vCard#logo";
    public static final 
    ObjectProperty logo = MODEL.createObjectProperty( "http://nwalsh.com/rdf/vCard#logo" );
    
    /** <p>A mobile email address of a person.</p> */
    public static final 
    String mobileEmail_URI = "http://nwalsh.com/rdf/vCard#mobileEmail";
    public static final 
    ObjectProperty mobileEmail = MODEL.createObjectProperty( "http://nwalsh.com/rdf/vCard#mobileEmail" );
    
    /** <p>A mobile phone number of a person.</p> */
    public static final 
    String mobileTel_URI = "http://nwalsh.com/rdf/vCard#mobileTel";
    public static final 
    ObjectProperty mobileTel = MODEL.createObjectProperty( "http://nwalsh.com/rdf/vCard#mobileTel" );
    
    /** <p>The components of the name of a person.</p> */
    public static final 
    String n_URI = "http://nwalsh.com/rdf/vCard#n";
    public static final 
    ObjectProperty n = MODEL.createObjectProperty( "http://nwalsh.com/rdf/vCard#n" );
    
    /** <p>An organization associated with a person.</p> */
    public static final 
    String org_URI = "http://nwalsh.com/rdf/vCard#org";
    public static final 
    ObjectProperty org = MODEL.createObjectProperty( "http://nwalsh.com/rdf/vCard#org" );
    
    /** <p>An email address unaffiliated with any particular organization or employer; 
     *  a personal email address.</p>
     */
    public static final 
    String personalEmail_URI = "http://nwalsh.com/rdf/vCard#personalEmail";
    public static final 
    ObjectProperty personalEmail = MODEL.createObjectProperty( "http://nwalsh.com/rdf/vCard#personalEmail" );
    
    /** <p>A photograph of a person.</p> */
    public static final 
    String photo_URI = "http://nwalsh.com/rdf/vCard#photo";
    public static final 
    ObjectProperty photo = MODEL.createObjectProperty( "http://nwalsh.com/rdf/vCard#photo" );
    
    /** <p>A sound (e.g., a greeting or pronounciation) of a person.</p> */
    public static final 
    String sound_URI = "http://nwalsh.com/rdf/vCard#sound";
    public static final 
    ObjectProperty sound = MODEL.createObjectProperty( "http://nwalsh.com/rdf/vCard#sound" );
    
    /** <p>A telephone number of a person.</p> */
    public static final 
    String tel_URI = "http://nwalsh.com/rdf/vCard#tel";
    public static final 
    ObjectProperty tel = MODEL.createObjectProperty( "http://nwalsh.com/rdf/vCard#tel" );
    
    /** <p>An (explicitly) unlabeled address of a person.</p> */
    public static final 
    String unlabeledAdr_URI = "http://nwalsh.com/rdf/vCard#unlabeledAdr";
    public static final 
    ObjectProperty unlabeledAdr = MODEL.createObjectProperty( "http://nwalsh.com/rdf/vCard#unlabeledAdr" );
    
    /** <p>An (explicitly) unlabeled email address of a person.</p> */
    public static final 
    String unlabeledEmail_URI = "http://nwalsh.com/rdf/vCard#unlabeledEmail";
    public static final 
    ObjectProperty unlabeledEmail = MODEL.createObjectProperty( "http://nwalsh.com/rdf/vCard#unlabeledEmail" );
    
    /** <p>An (explicitly) unlabeled phone number of a person.</p> */
    public static final 
    String unlabeledTel_URI = "http://nwalsh.com/rdf/vCard#unlabeledTel";
    public static final 
    ObjectProperty unlabeledTel = MODEL.createObjectProperty( "http://nwalsh.com/rdf/vCard#unlabeledTel" );
    
    /** <p>A URL associated with a person.</p> */
    public static final 
    String url_URI = "http://nwalsh.com/rdf/vCard#url";
    public static final 
    ObjectProperty url = MODEL.createObjectProperty( "http://nwalsh.com/rdf/vCard#url" );
    
    /** <p>A work address of a person.</p> */
    public static final 
    String workAdr_URI = "http://nwalsh.com/rdf/vCard#workAdr";
    public static final 
    ObjectProperty workAdr = MODEL.createObjectProperty( "http://nwalsh.com/rdf/vCard#workAdr" );
    
    /** <p>A work email address of a person.</p> */
    public static final 
    String workEmail_URI = "http://nwalsh.com/rdf/vCard#workEmail";
    public static final 
    ObjectProperty workEmail = MODEL.createObjectProperty( "http://nwalsh.com/rdf/vCard#workEmail" );
    
    /** <p>A work phone number of a person.</p> */
    public static final 
    String workTel_URI = "http://nwalsh.com/rdf/vCard#workTel";
    public static final 
    ObjectProperty workTel = MODEL.createObjectProperty( "http://nwalsh.com/rdf/vCard#workTel" );
    
    
    // see VocabularyGenerator#writeDatatypeProperties()
    /** <p>An additional part of a person's name.</p> */
    public static final 
    String additional_name_URI = "http://nwalsh.com/rdf/vCard#additional-name";
    public static final 
    DatatypeProperty additional_name = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#additional-name" );
    
    /** <p>The birthday of a person.</p> */
    public static final 
    String bday_URI = "http://nwalsh.com/rdf/vCard#bday";
    public static final 
    DatatypeProperty bday = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#bday" );
    
    /** <p>A category of a vCard.</p> */
    public static final 
    String category_URI = "http://nwalsh.com/rdf/vCard#category";
    public static final 
    DatatypeProperty category = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#category" );
    
    /** <p>A class (e.g., public, private, etc.) of a vCard.</p> */
    public static final 
    String class__URI = "http://nwalsh.com/rdf/vCard#class";
    public static final 
    DatatypeProperty class_ = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#class" );
    
    /** <p>The country of a postal address.</p> */
    public static final 
    String country_name_URI = "http://nwalsh.com/rdf/vCard#country-name";
    public static final 
    DatatypeProperty country_name = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#country-name" );
    
    /** <p>The extended address of a postal address.</p> */
    public static final 
    String extended_address_URI = "http://nwalsh.com/rdf/vCard#extended-address";
    public static final 
    DatatypeProperty extended_address = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#extended-address" );
    
    /** <p>A family name part of a person's name.</p> */
    public static final 
    String family_name_URI = "http://nwalsh.com/rdf/vCard#family-name";
    public static final 
    DatatypeProperty family_name = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#family-name" );
    
    /** <p>A formatted name of a person.</p> */
    public static final 
    String fn_URI = "http://nwalsh.com/rdf/vCard#fn";
    public static final 
    DatatypeProperty fn = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#fn" );
    
    /** <p>A given name part of a person's name.</p> */
    public static final 
    String given_name_URI = "http://nwalsh.com/rdf/vCard#given-name";
    public static final 
    DatatypeProperty given_name = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#given-name" );
    
    /** <p>An honorific prefix part of a person's name.</p> */
    public static final 
    String honorific_prefix_URI = "http://nwalsh.com/rdf/vCard#honorific-prefix";
    public static final 
    DatatypeProperty honorific_prefix = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#honorific-prefix" );
    
    /** <p>An honorific suffix part of a person's name.</p> */
    public static final 
    String honorific_suffix_URI = "http://nwalsh.com/rdf/vCard#honorific-suffix";
    public static final 
    DatatypeProperty honorific_suffix = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#honorific-suffix" );
    
    /** <p>The formatted version of a postal address (a string with embedded line breaks, 
     *  punctuation, etc.).</p>
     */
    public static final 
    String label_URI = "http://nwalsh.com/rdf/vCard#label";
    public static final 
    DatatypeProperty label = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#label" );
    
    /** <p>The latitude of a geographic location.</p> */
    public static final 
    String latitude_URI = "http://nwalsh.com/rdf/vCard#latitude";
    public static final 
    DatatypeProperty latitude = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#latitude" );
    
    /** <p>The locality (e.g., city) of a postal address.</p> */
    public static final 
    String locality_URI = "http://nwalsh.com/rdf/vCard#locality";
    public static final 
    DatatypeProperty locality = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#locality" );
    
    /** <p>The longitude of a geographic location</p> */
    public static final 
    String longitude_URI = "http://nwalsh.com/rdf/vCard#longitude";
    public static final 
    DatatypeProperty longitude = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#longitude" );
    
    /** <p>A mailer associated with a vCard.</p> */
    public static final 
    String mailer_URI = "http://nwalsh.com/rdf/vCard#mailer";
    public static final 
    DatatypeProperty mailer = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#mailer" );
    
    /** <p>Notes about a person on a vCard.</p> */
    public static final 
    String note_URI = "http://nwalsh.com/rdf/vCard#note";
    public static final 
    DatatypeProperty note = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#note" );
    
    /** <p>The name of an organization.</p> */
    public static final 
    String organization_name_URI = "http://nwalsh.com/rdf/vCard#organization-name";
    public static final 
    DatatypeProperty organization_name = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#organization-name" );
    
    /** <p>The name of a unit within an organization.</p> */
    public static final 
    String organization_unit_URI = "http://nwalsh.com/rdf/vCard#organization-unit";
    public static final 
    DatatypeProperty organization_unit = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#organization-unit" );
    
    /** <p>The post office box of a postal address.</p> */
    public static final 
    String post_office_box_URI = "http://nwalsh.com/rdf/vCard#post-office-box";
    public static final 
    DatatypeProperty post_office_box = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#post-office-box" );
    
    /** <p>The postal code (e.g., U.S. ZIP code) of a postal address.</p> */
    public static final 
    String postal_code_URI = "http://nwalsh.com/rdf/vCard#postal-code";
    public static final 
    DatatypeProperty postal_code = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#postal-code" );
    
    /** <p>The region (e.g., state or province) of a postal address.</p> */
    public static final 
    String region_URI = "http://nwalsh.com/rdf/vCard#region";
    public static final 
    DatatypeProperty region = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#region" );
    
    /** <p>The timestamp of a revision of a vCard.</p> */
    public static final 
    String rev_URI = "http://nwalsh.com/rdf/vCard#rev";
    public static final 
    DatatypeProperty rev = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#rev" );
    
    /** <p>A role a person plays within an organization.</p> */
    public static final 
    String role_URI = "http://nwalsh.com/rdf/vCard#role";
    public static final 
    DatatypeProperty role = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#role" );
    
    /** <p>A version of a person's name suitable for collation.</p> */
    public static final 
    String sort_string_URI = "http://nwalsh.com/rdf/vCard#sort-string";
    public static final 
    DatatypeProperty sort_string = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#sort-string" );
    
    /** <p>The street address of a postal address.</p> */
    public static final 
    String street_address_URI = "http://nwalsh.com/rdf/vCard#street-address";
    public static final 
    DatatypeProperty street_address = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#street-address" );
    
    /** <p>A person's title.</p> */
    public static final 
    String title_URI = "http://nwalsh.com/rdf/vCard#title";
    public static final 
    DatatypeProperty title = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#title" );
    
    /** <p>A timezone associated with a person.</p> */
    public static final 
    String tz_URI = "http://nwalsh.com/rdf/vCard#tz";
    public static final 
    DatatypeProperty tz = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#tz" );
    
    /** <p>A UID of a person's vCard.</p> */
    public static final 
    String uid_URI = "http://nwalsh.com/rdf/vCard#uid";
    public static final 
    DatatypeProperty uid = MODEL.createDatatypeProperty( "http://nwalsh.com/rdf/vCard#uid" );
    
    
    // see VocabularyGenerator#writeAnnotationProperties()
    
    // see VocabularyGenerator#writeOntClasses()
    /** <p>Resources that are vCard (postal) addresses.</p> */
    public static final 
    String Address_URI = "http://nwalsh.com/rdf/vCard#Address";
    public static final 
    OntClass Address = MODEL.createClass( "http://nwalsh.com/rdf/vCard#Address" );
    
    /** <p>Resources that are vCard geographic locations.</p> */
    public static final 
    String Geo_URI = "http://nwalsh.com/rdf/vCard#Geo";
    public static final 
    OntClass Geo = MODEL.createClass( "http://nwalsh.com/rdf/vCard#Geo" );
    
    /** <p>Resources that are vCard personal names.</p> */
    public static final 
    String Name_URI = "http://nwalsh.com/rdf/vCard#Name";
    public static final 
    OntClass Name = MODEL.createClass( "http://nwalsh.com/rdf/vCard#Name" );
    
    /** <p>Resources that are vCard organizations.</p> */
    public static final 
    String Organization_URI = "http://nwalsh.com/rdf/vCard#Organization";
    public static final 
    OntClass Organization = MODEL.createClass( "http://nwalsh.com/rdf/vCard#Organization" );
    
    /** <p>Resources that are vCards.</p> */
    public static final 
    String VCard_URI = "http://nwalsh.com/rdf/vCard#VCard";
    public static final 
    OntClass VCard = MODEL.createClass( "http://nwalsh.com/rdf/vCard#VCard" );
    
    
    // see VocabularyGenerator#writeOntIndividuals()
    
}
