package org.oucs.gaboto.entities;

import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.oucs.gaboto.entities.pool.GabotoEntityPool;
import org.oucs.gaboto.entities.utils.SimpleLiteralProperty;
import org.oucs.gaboto.model.GabotoSnapshot;

import com.hp.hpl.jena.rdf.model.Literal;
import com.hp.hpl.jena.rdf.model.Resource;
import com.hp.hpl.jena.rdf.model.Statement;


/**
 *<p>This class was automatically generated by Gaboto<p>
 */
public class Carpark extends Place {
	private int capacity;


	private static Map<String, List<Method>> indirectPropertyLookupTable;
	static{
		indirectPropertyLookupTable = new HashMap<String, List<Method>>();
		List<Method> list;

		try{
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	@Override
	public String getType(){
		return "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#Carpark";
	}

	@SimpleLiteralProperty(
		value = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#capacity",
		datatypeType = "javaprimitive",
		javaType = "int"
	)
	public int getCapacity(){
		return this.capacity;
	}

	@SimpleLiteralProperty(
		value = "http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#capacity",
		datatypeType = "javaprimitive",
		javaType = "int"
	)
	public void setCapacity(int capacity){
		this.capacity = capacity;
	}







	public void loadFromSnapshot(Resource res, GabotoSnapshot snapshot, GabotoEntityPool pool) {
		super.loadFromSnapshot(res, snapshot, pool);
		Statement stmt;

		stmt = res.getProperty(snapshot.getProperty("http://ns.ox.ac.uk/namespace/oxpoints/2009/02/owl#capacity"));
		if(null != stmt && stmt.getObject().isLiteral())
			this.setCapacity(((Literal)stmt.getObject()).getInt());

	}
	protected List<Method> getIndirectMethodsForProperty(String propertyURI){
		List<Method> list = super.getIndirectMethodsForProperty(propertyURI);
		if(null == list)
			return indirectPropertyLookupTable.get(propertyURI);
		
		else{
			List<Method> tmp = indirectPropertyLookupTable.get(propertyURI);
			if(null != tmp)
				list.addAll(tmp);
		}
		return list;
	}

}