/* CVS $Id: $ */
package org.oucs.gaboto.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from ontologies/rdfcon.owl 
 * @author Auto-generated by schemagen on 11 Mar 2009 08:56 
 */
public class RDFCON {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    
    public static final String hasContext_URI = "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#hasContext";
    public static final ObjectProperty hasContext = m_model.createObjectProperty( "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#hasContext" );
        
    
    
    public static final String hasDimension_URI = "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#hasDimension";
    public static final ObjectProperty hasDimension = m_model.createObjectProperty( "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#hasDimension" );
        
    
    
    public static final String hasTemporalDimension_URI = "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#hasTemporalDimension";
    public static final ObjectProperty hasTemporalDimension = m_model.createObjectProperty( "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#hasTemporalDimension" );
        
    
    
    public static final String ContextDescriptionGraph_URI = "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#ContextDescriptionGraph";
    public static final OntClass ContextDescriptionGraph = m_model.createClass( "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#ContextDescriptionGraph" );
        
    
    
    public static final String ContextGraph_URI = "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#ContextGraph";
    public static final OntClass ContextGraph = m_model.createClass( "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#ContextGraph" );
        
    
    
    public static final String GlobalKnowledgeGraph_URI = "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#GlobalKnowledgeGraph";
    public static final OntClass GlobalKnowledgeGraph = m_model.createClass( "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#GlobalKnowledgeGraph" );
        
    
    
    public static final String ResourceDescriptionGraph_URI = "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#ResourceDescriptionGraph";
    public static final OntClass ResourceDescriptionGraph = m_model.createClass( "http://ns.ox.ac.uk/namespace/rdfcon/2009/02/owl#ResourceDescriptionGraph" );
        
    
}
