/* CVS $Id: $ */
package org.oucs.gaboto.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from ontologies/rdfg.rdf 
 * @author Auto-generated by schemagen on 11 Mar 2009 08:56 
 */
public class RDFG {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.RDFS_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/2004/03/trix/rdfg-1/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The graphs associated with the subject and object are equivalent.</p> */
    
    public static final String equivalentGraph_URI = "http://www.w3.org/2004/03/trix/rdfg-1/equivalentGraph";
    public static final OntProperty equivalentGraph = m_model.createOntProperty( "http://www.w3.org/2004/03/trix/rdfg-1/equivalentGraph" );
        
    
    /** <p>The graph associated with the subject is a subgraph of a graph equivalent 
     *  to that associated with the object.</p>
     */
    
    public static final String subGraphOf_URI = "http://www.w3.org/2004/03/trix/rdfg-1/subGraphOf";
    public static final OntProperty subGraphOf = m_model.createOntProperty( "http://www.w3.org/2004/03/trix/rdfg-1/subGraphOf" );
        
    
    /** <p>An RDF graph (with intensional semantics).</p> */
    
    public static final String Graph_URI = "http://www.w3.org/2004/03/trix/rdfg-1/Graph";
    public static final OntClass Graph = m_model.createClass( "http://www.w3.org/2004/03/trix/rdfg-1/Graph" );
        
    
}
